# SniPyts

## Guess The Number

In [36]:
# Guess the number
import random

n = random.randrange(1, 10)
guess = int(input("Enter any number between 1 & 10: "))
while n != guess:
    if guess < n:
        print(" Too low")
        guess = int(input("Enter number again: "))
    elif guess > n:
        print("Too high")
        guess = int(input("Enter number again: "))
    else: 
        break
print("You guessed it right")

Too high
Too high
You guessed it right


## Calculate Mean, Median and Mode

In [37]:
# Calculate mean, median and mode
import random

# Mean
list = [random.randrange(10, 30) for i in range(10)]
mean = sum(list)/len(list)
print(f"Mean of {list}: {mean}")

# Median 
list = [random.randrange(10, 30) for i in range(10)]
list.sort()
if len(list) % 2 == 0:
    m1 = list[len(list)//2]
    m2 = list[len(list)//2 - 1]
    median = (m1 + m2)/2
else:
    median = list[len(list)//2]
print(f"Median of {list}: {median}")

# Mode
list = [12, 16, 20, 20, 12, 30, 25, 23, 24, 20]
frequency = {}
for i in list:
    frequency.setdefault(i, 0)
    frequency[i] += 1

frequent = max(frequency.values())
for i, j in frequency.items():
    if j == frequent:
        mode = i
print(f"Mode of {list}: {mode}")

# Mode: Simpler code with dictionary comprehension
list = [12, 16, 20, 20, 12, 30, 25, 23, 24, 20]
freq = {key: list.count(key) for key in list} 
mode = max(freq, key=freq.get)
print(f"Mode of {list}: {mode}")


Mean of [19, 13, 19, 16, 21, 17, 22, 10, 11, 23]: 17.1
Median of [11, 12, 15, 19, 20, 24, 26, 27, 28, 28]: 22.0
Mode of [12, 16, 20, 20, 12, 30, 25, 23, 24, 20]: 20
Mode of [12, 16, 20, 20, 12, 30, 25, 23, 24, 20]: 20


## Authenticate Password

In [38]:
# Authenticate password
import getpass

database = {"ravi.billa": "123456", "billa.ravi": "654321"}
username = input("Enter your username: ")

if username in database.keys():
    password = getpass.getpass("Enter your password: ")
    
    for user, pwd in database.items():
         if username == user:
                while password != database.get(user):
                    password = getpass.getpass("Incorrect password! \nEnter your password again: ")
                break
    print("User verfied !")
else:
    print("User doesn't exist!")

User doesn't exist!


## Send Email

In [39]:
# Send email
import os
import random
import smtplib

def send_email():
    user = input("Enter your name >>")
    email = input("Enter your e-mail >>")
    message = (f"Dear {user}, weclome to snipyts")
    s = smtplib.SMTP('smtp.gmail.com', 587)
    s.starttls()
    s.login("Your Gmail Account", "Your App Password")
    s.sendmail('&&&&&&&', email, message)
    print("Email sent")

send_email()


SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d8-20020a170903230800b001db5bdd5e33sm7410987plh.48 - gsmtp')

## 

## Calculate Age

In [40]:
# Calculate age
import datetime

def calc_age(y, m, d):
    today = datetime.datetime.now().date()
    dob = datetime.date(y, m, d)
    age = int((today - dob).days/365.25)
    print(f"Your age is: {age}")

calc_age(1981, 7, 15)

Your age is: 42


## Group Anagrams

In [3]:
from collections import defaultdict
dfdict = defaultdict()

In [5]:
# Group anagrams
from collections import defaultdict

def group_anagrams(words):
    dfdict = defaultdict(list)
    for w in words:
        sorted_word = "".join(sorted(w))
        dfdict[sorted_word].append(w)
    
    return dfdict.values()

words = ["tea", "eat", "bat", "ate", "arc", "car"]
print(f"Grouped anagrams: {group_anagrams(words)}")


Grouped anagrams: dict_values([['tea', 'eat', 'ate'], ['bat'], ['arc', 'car']])


## Find Missing Numbers

In [8]:
# Find missing numbers
def find_missing_numbers(lst):
    nums = set(lst)
    missing_nums = []
    for i in range(min(lst), max(lst)):
        if i not in nums:
            missing_nums.append(i)
    
    return missing_nums

num_list = [1, 2, 3, 5, 6, 8, 9, 10, 12, 16]    
print(f"Missing numbers in the list: {find_missing_numbers(num_list)}")


Missing numbers in the list: [4, 7, 11, 13, 14, 15]


## Group Elements by Index

In [52]:
# Group elements by index
def group_elements_by_index(inputLists):
    outputLists = []
    for j in range(len(inputLists[0])):
        outputLists.append([])
        for i in range (len(inputLists)):
            outputLists[j].append(inputLists[i][j])
    
    return(outputLists)

Lists = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
print(f"Grouped elements by index: {group_elements_by_index(Lists)}")


Grouped elements by index: [[10, 40, 70], [20, 50, 80], [30, 60, 90]]


## Calculate Code Execution Time

In [77]:
# Calculate code execution time
from time import time
import numpy as np

start = time()
# Sample matrix mulitplication code
a = np.random.randint(10, size=(10, 10))
b = np.random.randint(10, size=(10, 10))
c = np.matmul(a, b)
print(c)
end = time()

print(f"Code executioin time: {round((end - start)*1000, 2)} ms")


[[205 194 265 280 240 230 248  90 250 271]
 [213 192 160 157 189 117 197 121 238 247]
 [179 144 190 221 161 146 163 117 225 254]
 [251 169 255 298 236 239 294 193 335 368]
 [238 205 245 283 252 213 210 155 253 247]
 [204 110 218 271 202 228 208 180 263 277]
 [155 196 150 185 155 143 149  65 152 198]
 [203 174 199 255 194 168 231 105 205 246]
 [261 223 255 305 275 209 232 144 270 274]
 [181 148 175 197 201 179 184  73 188 232]]
Code executioin time: 0.94 ms
